application: stellar-perigee-88406
version: 1
runtime: php
api_version: 2
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.php
